transfusion/urls.py
from django.views.generic.base import TemplateView

__author__ = 'Sam'

from django.conf.urls import patterns, url

from transfusion import views


urlpatterns = patterns(
    '',

    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^create/$', views.create_account, name='create_account'),

    url(r'^t/(?P<teacher>[^/]+)/$', views.teacher_profile, name='teacher_profile'),
    url(r'^t/(?P<teacher>[^/]+)/c/(?P<course>[0-9]+)/$', views.course, name='course'),
    url(r'^sign_in/$', views.sign_in, name="sign_in"),
    url(r'^sign_out/$', views.sign_out, name="sign_out"),

    url(r'^add_course/$', views.add_course, name='add_course'),

    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/$', views.edit_course, name='edit_course'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/add_assignment/$', views.add_assignment, name='add_assignment'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/edit_assignment/(?P<assignment_id>[0-9]+)/$', views.edit_assignment, name='edit_assignment'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/delete_assignment/(?P<assignment_id>[0-9]+)/$', views.delete_assignment, name='delete_assignment'),

    url(r'^edit_course/(?P<course_id>[0-9]+)/info/$', views.edit_course_info, name='edit_course_info'),

    url(r'^edit_course/(?P<course_id>[0-9]+)/add_link/$', views.add_link, name='add_link'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/edit_link/(?P<link_id>[0-9]+)/$', views.edit_link, name='edit_link'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/delete_link/(?P<link_id>[0-9]+)/$', views.delete_link, name='delete_link'),

    url(r'^edit_course/(?P<course_id>[0-9]+)/add_file/$', views.add_file, name='add_file'),
    url(r'^edit_course/(?P<course_id>[0-9]+)/delete_file/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),

    url(r'^preferences/$', views.preferences, name='preferences'),
    url(r'^preferences/password/$', views.change_password, name='change_password'),

    url(r'^delete/$', views.delete_things, name='delete_things'),

    url('^students/$', TemplateView.as_view(template_name='transfusion/for_students.html'), name="for_students"),
    url('^teachers/$', TemplateView.as_view(template_name='transfusion/for_teachers.html'), name="for_teachers"),

    url(r'download_file/(?P<file_id>[0-9]+)/$', views.download_file, name='download_file'),

)

transfusion_v2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('transfusion.urls', namespace='transfusion'))
]

transfusion/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone


class TeacherProfile(models.Model):
    user = models.OneToOneField(User)
    school = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.get_full_name()


class Course(models.Model):
    user = models.ForeignKey(User)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    short_description = models.TextField(blank=True, null=True, max_length=500)

    def __str__(self):
        return self.name + " (" + self.user.get_full_name() + ")"


class Assignment(models.Model):
    course = models.ForeignKey(Course)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    due_date = models.DateField()

    def __str__(self):
        return self.name + " (" + self.course.name + ")"

    @property
    def is_past_due(self):
        if timezone.now().date() >= self.due_date:
            return True
        return False


class Link(models.Model):
    course = models.ForeignKey(Course)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    address = models.TextField()

    def __str__(self):
        return self.name + " (" + self.course.name + ")"


class File(models.Model):
    course = models.ForeignKey(Course)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    filename = models.TextField()
    path = models.TextField()

    def __str__(self):
        return self.name + " (" + self.course.name + ")"

transfusion/views.py
import os
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db.models.query_utils import Q
from django.db.utils import IntegrityError
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.utils.encoding import smart_str
from transfusion.models import Course, Assignment, Link, TeacherProfile, File
from transfusion_v2.settings import BASE_DIR, MEDIA_ROOT


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'transfusion/index.html')
    else:
        return render(request, 'transfusion/logged_in_index.html')


def search(request):

    term = request.GET.get('term')

    if (not term == "") and (term is not None):
        results = User.objects.filter(Q(username__icontains=term) | Q(last_name__icontains=term))
    else:
        results = None

    context = {
        'term': term,
        'results': results
    }
    
    return render(request, 'transfusion/search.html', context)


def teacher_profile(request, teacher):
    user = User.objects.get(username=teacher)

    context = {
        'user': user,
    }

    return render(request, 'transfusion/teacher_profile.html', context)


def course(request, teacher, course):
    user = User.objects.get(username=teacher)
    t_course = Course.objects.get(id=course)
    assignments = t_course.assignment_set.order_by('-due_date')
    links = t_course.link_set.order_by('-id')
    files = t_course.file_set.order_by('-id')

    context = {
        'user': user,
        'course': t_course,
        'assignments': assignments,
        'links': links,
        'files': files
    }

    return render(request, 'transfusion/course.html', context)


def sign_in(request):
    if request.method != "POST":
        messages.error(request, "Please login first.")
        return HttpResponseRedirect(reverse("transfusion:index"))

    username = request.POST.get("username")
    password = request.POST.get("password")

    user = authenticate(username=username, password=password)

    if user is not None:
        if user.is_active:
            login(request, user)
        else:
            messages.error(request, "Your user account has been deactivated.")
    else:
        messages.error(request, "Account not found, perhaps you entered your password incorrectly?")
        
    return HttpResponseRedirect(reverse("transfusion:index"))


def sign_out(request):
    logout(request)
    messages.info(request, "Logged out successfully.")
    return HttpResponseRedirect(reverse('transfusion:index'))


@login_required
def edit_profile(request):
    if request.method != "POST":
        return render(request, 'transfusion/edit_teacher_info.html')
    else:
        school = request.POST.get("school")
        description = request.POST.get("description")

        profile = request.user.teacherprofile

        profile.school = school
        profile.description = description

        profile.save()

        return HttpResponseRedirect(reverse('transfusion:index'))



@login_required
def edit_course(request, course_id):

    try:
        course = Course.objects.get(id=course_id, user=request.user)
    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    assignments = course.assignment_set.order_by('-due_date')
    links = course.link_set.order_by('-id')
    files = course.file_set.order_by('-id')

    context = {
        'course': course,
        'assignments': assignments,
        'links': links,
        'files': files
    }

    return render(request, 'transfusion/edit_course.html', context)


@login_required
def edit_course_info(request, course_id):
    try:
        course = Course.objects.get(id=course_id, user=request.user)
    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    if request.method == "POST":
        name = request.POST.get('name')
        short_description = request.POST.get('short_description')
        description = request.POST.get('description')

        course.name = name
        course.short_description = short_description
        course.description = description

        course.save()

        messages.success(request, "Course changed.")

        return HttpResponseRedirect(reverse('transfusion:edit_course', kwargs={'course_id': course_id}))

    else:

        context = {
            'course': course
        }

        return render(request, 'transfusion/edit_course_info.html', context)


@login_required
def add_assignment(request, course_id):
    try:
        course = Course.objects.get(id=course_id, user=request.user)
    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    if request.method == "POST":
        name = request.POST.get('name')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')

        new_assignment = Assignment(name=name, due_date=due_date, description=description, course=course)
        try:
            new_assignment.save()
        except ValidationError:
            messages.error(request, "Unable to save assignment. Please try again.")

            context = {
                'course': course
            }
            return render(request, 'transfusion/add_assignment.html', context)

        messages.success(request, "Assignment added.")

        return HttpResponseRedirect(reverse('transfusion:edit_course', kwargs={'course_id': course.id}))

    else:
        context = {
            'course': course
        }
        return render(request, 'transfusion/add_assignment.html', context)


@login_required
def edit_assignment(request, course_id, assignment_id):
    try:
        course = Course.objects.get(id=course_id, user=request.user)
        assignment = Assignment.objects.get(id=assignment_id, course=course)

    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    except Assignment.DoesNotExist:
        messages.warning(request, "This assignment does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    if request.method == "POST":
        name = request.POST.get('name')
        due_date = request.POST.get('due_date')
        description = request.POST.get('description')

        assignment.name = name
        assignment.due_date = due_date
        assignment.description = description

        try:
            assignment.save()
        except ValidationError:
            messages.error(request, "Unable to save assignment. Please try again.")
            context = {
                'course': course
            }
            return render(request, 'transfusion/add_assignment.html', context)

        messages.success(request, "Assignment changed.")

        return HttpResponseRedirect(reverse('transfusion:edit_course', kwargs={'course_id': course.id}))

    else:
        context = {
            'course': course,
            'assignment': assignment
        }
        return render(request, 'transfusion/edit_assignment.html', context)


@login_required
def delete_assignment(request, course_id, assignment_id):
    try:
        assignment = Assignment.objects.get(id=assignment_id, course_id=course_id)
        assignment.delete()
        messages.success(request, "Assignment deleted.")
    except Assignment.DoesNotExist:
        messages.warning(request, "This assignment does not exist.")

    return HttpResponseRedirect(reverse('transfusion:edit_course', kwargs={'course_id': course_id}))


@login_required
def add_link(request, course_id):
    try:
        course = Course.objects.get(id=course_id, user=request.user)
    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    if request.method == "POST":
        name = request.POST.get('name')
        address = request.POST.get('address')
        description = request.POST.get('description')

        new_link = Link(name=name, address=address, description=description, course=course)
        try:
            new_link.save()
        except ValidationError:
            messages.error(request, "Unable to save link. Please try again.")

            context = {
                'course': course
            }
            return render(request, 'transfusion/add_link.html', context)

        messages.success(request, "Link added.")

        return HttpResponseRedirect(reverse('transfusion:edit_course', kwargs={'course_id': course.id}))

    else:
        context = {
            'course': course
        }
        return render(request, 'transfusion/add_link.html', context)


@login_required
def edit_link(request, course_id, link_id):
    try:
        course = Course.objects.get(id=course_id, user=request.user)
        link = Link.objects.get(id=link_id, course=course)

    except Course.DoesNotExist:
        messages.warning(request, "This course does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    except Link.DoesNotExist:
        messages.warning(request, "This link does not exist.")
        return HttpResponseRedirect(reverse('transfusion:index'))

    if request.method == "POST":
        name = request.POST.get('name')
        address = request.POST.get('address')
        description = request.POST.get('description')

        link.name = name

transfusion/templates/transfusion/change_password.html
{% extends 'transfusion/base.html' %}
{% block title %}Change Password{% endblock %}

{% block nav %}
    {% include 'transfusion/logged_in_header.html' %}
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'transfusion:index' %}">{{ user.get_full_name }}</a></li>
                <li><a href="{% url 'transfusion:preferences' %}">Preferences</a></li>
                <li class="active">Change Password</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form role="form" method="post" onsubmit="return validatePassword();">
                {% csrf_token %}
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h3 class="panel-title">Change Password &nbsp;<button class="btn btn-success btn-sm">Save <span class="glyphicon glyphicon-save"></span></button></h3>
                    </div>
                    <div class="panel-body">
                        <div class="input-group">
                            <label>Current Password</label>
                            <input class="form-control" type="password" name="current_password" required="true">
                        </div>
                        <hr>
                        <div class="input-group">
                            <label>New Password</label>
                            <input class="form-control" type="password" name="new_password" id="new_password" required="true">
                        </div>
                        <br>
                        <div class="input-group">
                            <label>Retype New Password</label>
                            <input class="form-control" type="password" name="new_password_repeat" id="new_password_repeat" required="true">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
function validatePassword() {
    if($("#new_password").val() === $("#new_password_repeat").val()) {
        return true;
    } else {
        alert("Your new passwords do not match. Please try again.");
        return false;
    }
}
</script>
{% endblock %}

transfusion/templates/transfusion/edit_course.html
{% extends 'transfusion/base.html' %}
{% block title %}{{ user.get_full_name }}{% endblock %}

{% block nav %}
    {% include 'transfusion/logged_in_header.html' %}
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'transfusion:index' %}">{{ user.get_full_name }}</a></li>
                <li class="active">{{ course.name }}</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ course.name }} &nbsp;<button onclick="window.location='{% url 'transfusion:edit_course_info' course_id=course.id %}';" class="btn btn-info btn-sm">Edit <span class="glyphicon glyphicon-edit"></span></button>&nbsp;<button onclick="$('#danger_zone').slideToggle();" class="btn btn-sm btn-warning">Delete... <span class="glyphicon glyphicon-remove-sign"></span></button></h3>
                </div>
                <div class="panel-body">
                    <p><strong>Short Description</strong></p>
                    <p>{{ course.short_description }}</p>
                    <p><strong>Description</strong></p>
                    <p>{{ course.description|safe }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="display: none;" id="danger_zone">
        <div class="col-md-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Danger Zone</h3>
                </div>
                <div class="panel-body">
                    <form role="form" onsubmit="return prompt('Are you sure you wish to continue? Type YES to confirm.') === 'YES';" class="form-inline" action="{% url 'transfusion:delete_things' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="course_id" value="{{ course.id }}">
                        <div class="input-group form-group has-error">
                            <div class="input-group-addon">Password</div>
                            <input class="form-control" type="password" name="password" required="true">
                        </div>
                        <button name="assignments" class="btn btn-danger">Delete All Assignments</button>
                        <button name="links" class="btn btn-danger">Delete All Links</button>
                        <button name="files" class="btn btn-danger">Delete All Files</button>
                        <button name="course" class="btn btn-warning">Delete Course</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Assignments &nbsp;<button onclick="window.location='{% url 'transfusion:add_assignment' course_id=course.id %}';" class="btn btn-default btn-sm">Add <span class="glyphicon glyphicon-plus"></span></button></h3>
                </div>
                <div class="panel-body">
                    {% if assignments %}
                        {% for assignment in assignments %}
                            <div class="well">
                                <h4>{{ assignment.name }}&nbsp;<br><small{% if assignment.is_past_due %} style="color: firebrick;"{% endif %}> Due: {{ assignment.due_date }}</small></h4>
                                <p>{{ assignment.description|safe }}</p>
                                <button onclick="window.location='{% url 'transfusion:edit_assignment' course_id=course.id assignment_id=assignment.id %}';" class="btn btn-info btn-sm">Edit <span class="glyphicon glyphicon-edit"></span></button>
                                <button onclick="if(confirm('Are you sure you wish to delete this assignment?')) { window.location = '{% url 'transfusion:delete_assignment' course_id=course.id assignment_id=assignment.id %}' }" class="btn btn-danger btn-sm">Delete <span class="glyphicon glyphicon-remove"></span></button>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h4>No assignments exist. </h4>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Links &nbsp;<button onclick="window.location='{% url 'transfusion:add_link' course_id=course.id %}';" class="btn btn-default btn-sm">Add <span class="glyphicon glyphicon-plus"></span></button></h3>
                </div>
                <div class="panel-body">
                    {% if links %}
                        {% for link in links %}
                            <div class="well">
                                <h4><a href="{{ link.address }}" target="_blank">{{ link.name }}</a></h4>
                                <p>{{ link.description|safe }}</p>
                                <p><small><a href="{{ link.address }}" target="_blank">{{ link.address }}</a></small></p>
                                <button onclick="window.location='{% url 'transfusion:edit_link' course_id=course.id link_id=link.id %}';" class="btn btn-info btn-sm">Edit <span class="glyphicon glyphicon-edit"></span></button>
                                <button onclick="if(confirm('Are you sure you wish to delete this link?')) { window.location = '{% url 'transfusion:delete_link' course_id=course.id link_id=link.id %}' }" class="btn btn-danger btn-sm">Delete <span class="glyphicon glyphicon-remove"></span></button>

                            </div>
                        {% endfor %}
                    {% else %}
                        <h4>No links exist. </h4>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Files &nbsp;<button onclick="window.location='{% url 'transfusion:add_file' course_id=course.id %}';" class="btn btn-default btn-sm">Add <span class="glyphicon glyphicon-plus"></span></button></h3>
                </div>
                <div class="panel-body">
                    {% if files %}
                        {% for file in files %}
                            <div class="well">
                                <h4>{{ file.name }}</h4>
                                <h4><small>{{ file.filename }}</small></h4>
                                <p>{{ file.description|safe }}</p>
                                <button onclick="window.location='{% url 'transfusion:download_file' file_id=file.id %}';" class="btn btn-info btn-sm">Download <span class="glyphicon glyphicon-download-alt"></span></button>
                                <button onclick="if(confirm('Are you sure you wish to delete this file?')) { window.location = '{% url 'transfusion:delete_file' course_id=course.id file_id=file.id %}' }" class="btn btn-danger btn-sm">Delete <span class="glyphicon glyphicon-remove"></span></button>

                            </div>
                        {% endfor %}
                    {% else %}
                        <h4>No files exist. </h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

transfusion/templates/transfusion/logged_in_header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'transfusion:index' %}">{{ user.get_full_name }}<span class="sr-only">(Teacher Index)</span></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Courses <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% if user.course_set.count > 0 %}
                            {% for a_course in user.course_set.all %}
                                <li><a href="{% url 'transfusion:edit_course' course_id=a_course.id %}">{{ a_course.name }}</a></li>
                            {% endfor %}
                        {% else %}
                            <li><a href="{% url 'transfusion:add_course' %}"><i>None &mdash; Create a Course</i></a></li>
                        {% endif %}
                    </ul>
                </li>
                <li><a href="{% url 'transfusion:add_course' %}">Add Course</a></li>
                <li><a href="{% url 'transfusion:preferences' %}">Preferences</a></li>
                <li><a href="{% url 'transfusion:sign_out' %}">Log Out</a></li>
            </ul>
        </div>
    </div>
</nav>

transfusion/templates/transfusion/search.html
{% extends 'transfusion/base.html' %}
{% block title %}Search{% endblock %}

{% block nav %}
    {% include 'transfusion/index_header.html' %}
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Teacher Search</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">

                    <form class="form" action="" method="get">
                        <div class="input-group">
                            <span class="input-group-addon">Results for</span>
                            <input type="text" class="form-control" value="{% if term != None %}{{ term }}{% endif %}" name="term">
                        <span class="input-group-btn">
                          <button class="btn btn-default" type="submit">Search Again</button>
                        </span>
                        </div>
                    </form>
                </div>
                <div class="panel-body">
                    {% if results %}
                        {% for result in results %}
                            <div class="well">
                                <h4><a href="{% url 'transfusion:teacher_profile' teacher=result.username %}">{{ result.get_full_name }}</a></h4>
                                {% if result.course_set %}
                                    <ul>
                                        {% for course in result.course_set.all %}
                                            <li><a href="{% url 'transfusion:course' teacher=result.username course=course.id %}">{{ course.name }}</a>{% if course.short_description %} &mdash; {{ course.short_description }}{% endif %}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <h3>No results found.</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

transfusion/templates/transfusion/teacher_profile.html
{% extends 'transfusion/base.html' %}
{% block title %}{{ user.get_full_name }}{% endblock %}

{% load markdown_deux_tags %}

{% block nav %}
    {% include 'transfusion/teacher_header.html' %}
{% endblock %}


{% block main_content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="active">{{ user.get_full_name }}</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">About {{ user.get_full_name }}</h3>
                </div>
                <div class="panel-body">
                    <p><strong>School: </strong>{{ user.teacherprofile.school }}</p>
                    <p>{{ user.teacherprofile.description|safe }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Courses</h3>
                </div>
                <div class="panel-body">
                    {% for course in user.course_set.all %}
                        <div class="well">
                            <h5><a href="{% url 'transfusion:course' teacher=user.username course=course.id %}">{{ course.name }}</a></h5>
                            {% if course.short_description %}
                                <p>{{ course.short_description }}</p>
                            {% endif %}
                            <div class="row">
                                <div class="col-md-4">
                                    <a href="{% url 'transfusion:course' teacher=user.username course=course.id %}#assignments" style="width: 100%; margin-top: 2px; margin-bottom: 2px;" class="btn btn-sm btn-info"><strong>{{ course.assignment_set.count }}</strong> assignment{{ course.assignment_set.count|pluralize }}</a>
                                </div>
                                <div class="col-md-4">
                                    <a href="{% url 'transfusion:course' teacher=user.username course=course.id %}#links" style="width: 100%; margin-top: 2px; margin-bottom: 2px;" class="btn btn-sm btn-success"><strong>{{ course.link_set.count }}</strong> link{{ course.link_set.count|pluralize }}</a>
                                </div>
                                <div class="col-md-4">
                                    <a href="{% url 'transfusion:course' teacher=user.username course=course.id %}#files" style="width: 100%; margin-top: 2px; margin-bottom: 2px;" class="btn btn-sm btn-primary"><strong>{{ course.file_set.count }}</strong> file{{ course.file_set.count|pluralize }}</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}